### ISSUE TITLE
Option to generate XSLT from EBNF

### ISSUE THREAD

**Issue by cwindeln** [GuntherRademacher/ebnf-convert#19]
Thank you very much for your great tool. In the online tool, there is the option to generate an XSLT from EBNF but I could not found this in ebnf-convert. Did I miss something?

Thank you,
Christine

**Comment by GuntherRademacher** [comment]
Sorry, but ebnf-convert is for converting grammars, and the output format is either W3C-style EBNF, or an XML representation of the same. Either can be generated both in the [online tool](https://www.bottlecaps.de/ebnf-convert/) and in the command-line tool. XSLT does not come into play here - except for a non-advertised `-xslt` option in the command-line tool, but that is for using its built-in XSLT-coded parsers, which are meant primarily as additional tests for [REx Parser Generator](https://www.bottlecaps.de/rex).

An option to "generate XSLT from EBNF" however is available in [REx Parser Generator](https://www.bottlecaps.de/rex). Use option `-xslt` there to generate a parser in XSLT for your grammar in W3C-style EBNF.

Note: both the [ebnf-convert online tool](https://www.bottlecaps.de/ebnf-convert/) and [REx Parser Generator](https://www.bottlecaps.de/rex) are IPv6-only.

**Comment by mkraetke** [comment]
Since I cannot access the ReX Parser Generator without IPV6, do you plan to put it on GitHub?

**Comment by GuntherRademacher** [comment]
> do you plan to put it on GitHub?

That will happen before the end of this year.
